spring:
  application:
    name: dcsProject
  datasource:
    url: jdbc:mysql://localhost:3306/dcs_db?serverTimezone=UTC  # MySQL 서버 시간대 설정 (UTC)
    username: root
    password: 'diwo0206^'
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC  # Hibernate가 사용할 시간대 설정 (UTC)
  
  resources:
    static-locations: classpath:/static/  # 정적 리소스 위치 설정
  mvc:
    view:
      prefix: /WEB-INF/views/  # JSP 파일 위치
      suffix: .jsp  # JSP 파일 확장자
